### ISSUE TITLE
Creating an interactive task with Java panics

### ISSUE THREAD

**Issue by chermehdi** [chermehdi/go-egor#60]
When reaching the Main class name section, egor panics with an error like: 

```

panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/chermehdi/egor/commands.fillTaskFromQuestions(0xc00021fc48, 0xa35340, 0xc000010010, 0x1, 0xc00021fc58)
        /home/maxheap/dev/go/src/github.com/chermehdi/go-egor/commands/create.go:88 +0x4d1
github.com/chermehdi/egor/commands.CreateTaskAction(0xc0002eab40, 0x2, 0x2)
        /home/maxheap/dev/go/src/github.com/chermehdi/go-egor/commands/create.go:123 +0x2a4
github.com/urfave/cli/v2.(*Command).Run(0xd9d7c0, 0xc0002eaa00, 0x0, 0x0)
        /home/maxheap/dev/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/command.go:161 +0x4e0
github.com/urfave/cli/v2.(*App).RunContext(0xc0001dc900, 0xa3ef00, 0xc00002c328, 0xc000020180, 0x3, 0x3, 0x0, 0x0)
        /home/maxheap/dev/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:302 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
        /home/maxheap/dev/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:211
main.main()
        /home/maxheap/dev/go/src/github.com/chermehdi/go-egor/main.go:79 +0x399
```

**Comment by chermehdi** [comment]
Fixed by #61
