### ISSUE TITLE
Running is broken when test has no output

### ISSUE THREAD

**Issue by Eroui** [chermehdi/go-egor#68]
Creating a test case without output and then trying to run your task solution  breaks.

```
❯ egor  r
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/chermehdi/egor/commands.RunAction(0xc000098580, 0x0, 0x0)
	.../go/src/github.com/go-egor/commands/run.go:512 +0x68c
github.com/urfave/cli/v2.(*Command).Run(0x199fa80, 0xc000098380, 0x0, 0x0)
	.../go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/command.go:161 +0x4e0
github.com/urfave/cli/v2.(*App).RunContext(0xc000082300, 0x163e4a0, 0xc000028320, 0xc00000e0a0, 0x2, 0x2, 0x0, 0x0)
	...go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:302 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
	.../go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:211
main.main()
...
```

**Comment by chermehdi** [comment]
This happens because egor supposes that the length of the output files is the same as input files.
